version: "3.7"

services:
  server:
    container_name: server
    build:
      context: src/
      dockerfile: Dockerfile
    command: [
      "uvicorn", 
      "main:app",
      "--host", "0.0.0.0", 
      "--port", "8090", 
      "--reload"
    ]
    ports:
      - 8090:8090
    volumes:
      - ./src:/app/src

  streamlit:
    container_name: streamlit
    build:
      context: streamlit/
      dockerfile: Dockerfile
    depends_on:
      - server
    command: [
      "streamlit", 
      "run", 
      "test.py",
    ]
    ports:
      - 8501:8501
    volumes:
      - ./src:/app/src

  nginx_proxy:
    image: nginx:latest
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx_proxy
    networks:
      - default
    depends_on:
      - server