version: "3.7"

services:
  server:
    image: shrack-ml
    command: [
      "uvicorn", 
      "main:app",
      "--host", "0.0.0.0", 
      "--port", "8080", 
      "--reload"
    ]
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src